import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import ConditionalNavbar from "@/components/Navbar/ConditionalNavbar";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer";

// เก็บ Toaster ไว้
import { Toaster } from "sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tobacco Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ConditionalNavbar>
            <Navbar />
          </ConditionalNavbar>
          
          {children}
          
          <ConditionalNavbar>
            <Footer />
          </ConditionalNavbar>
        </Providers>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  )
}